### ISSUE TITLE
Problems about predict_i2v

### ISSUE THREAD

**Issue by dctnorin** [aigc-apps/CogVideoX-Fun#10]
Something went wrong, when I used the predict_i2v.py.
ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.

It seems like the error came from the resolution, but I didn't change anything. Please guide me to solve this problem.

![2024-09-19 180624](https://github.com/user-attachments/assets/04ebff04-8194-43ee-b82c-07629872e919)

**Comment by bubbliiiing** [comment]
Please pull the latest code

**Comment by dctnorin** [comment]
> Please pull the latest code

The code can work now, thanks for your guidance.
