### ISSUE TITLE
no module named tinychat

### ISSUE THREAD

**Issue by liushuhao1130** [aigc-apps/CogVideoX-Fun#104]
I want to follow the video caption, but meet an error no module named tinychat, and I don not find where to download it.

**Comment by hkunzhe** [comment]
@liushuhao1130 Hi, the video caption was copied from EasyAnimate. You can use the latest video caption from https://github.com/aigc-apps/EasyAnimate/tree/main/easyanimate/video_caption

**Comment by dvschultz** [comment]
Can I submit a PR to pull over the EasyAnimate updates? Its kind of annoying to not have any note in the repo that its out of date.

**Comment by hkunzhe** [comment]
@dvschultz, we'll update CogVideoX-Fun recently. Please stay tuned :)
