### ISSUE TITLE
Support for Diffusers?

### ISSUE THREAD

**Issue by tin2tin** [aigc-apps/CogVideoX-Fun#13]
I tried to just swap the Fun weights with the original CogVideoX-5b weights, doing inference with Diffusers. That didn't work. 
So, is it possible to run CogVideoX-Fun thorugh Diffusers? Are there any code examples?

**Comment by bubbliiiing** [comment]
The file path is incorrect.

**Comment by bubbliiiing** [comment]
Your meaning is to integrate into the diffusers repository, right?

**Comment by tin2tin** [comment]
Yes, how can CogVideoX-Fun used trough the Diffusers library? There is already support for the original CogVideoX in Diffusers.

**Comment by bubbliiiing** [comment]
> 是的，如何通过 Diffusers 库使用 CogVideoX-Fun？Diffusers 中已经支持原始 CogVideoX。

This will take some time to develop.
