### ISSUE TITLE
Unable to run under windows, problem with requirements.txt

### ISSUE THREAD

**Issue by randaller** [aigc-apps/CogVideoX-Fun#14]
I am trying to run under windows without any success, xformers & diffusers won't build, conflicting with torch in requirements.txt.

Please specify the requirements for windows more precisely, if possible.

Steps:
```bash
conda create -n cogvideox python=3.10
conda activate cogvideox
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia  // this installs torch-gpu 2.4, tried also with pip install torch==2.2.0 without any success, got torch-cpu conflict
pip install -r requirements.txt // <- failure, xformers won't build (builds well in all my other venvs!!!)
```

![image](https://github.com/user-attachments/assets/82b41db8-657e-45c0-baff-0b366152c927)

**Comment by realisticdreamer114514** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5865

**Comment by randaller** [comment]
Thanks, it worked. Installed xformers from facebook wheel, deepspeed still not builds, but inference works well without deepspeed.
