### ISSUE TITLE
how to load from cogvideo official pretrained model?

### ISSUE THREAD

**Issue by jianlong-yuan** [aigc-apps/CogVideoX-Fun#18]

**Comment by bubbliiiing** [comment]
Only support the t2v model.

**Comment by jianlong-yuan** [comment]
How to resume dataset ?

**Comment by bubbliiiing** [comment]
Set --resume_from_checkpoint="latest"

**Comment by jianlong-yuan** [comment]
> Set --resume_from_checkpoint="latest"


By examining the code, it can be seen that only the parameters and epoch have been loaded, and the data iters has not been resumed.


    if args.resume_from_checkpoint:
        if args.resume_from_checkpoint != "latest":
            path = os.path.basename(args.resume_from_checkpoint)
        else:
            # Get the most recent checkpoint
            dirs = os.listdir(args.output_dir)
            dirs = [d for d in dirs if d.startswith("checkpoint")]
            dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
            path = dirs[-1] if len(dirs) > 0 else None

        if path is None:
            accelerator.print(
                f"Checkpoint '{args.resume_from_checkpoint}' does not exist. Starting a new training run."
            )
            args.resume_from_checkpoint = None
            initial_global_step = 0
        else:
            global_step = int(path.split("-")[1])

            initial_global_step = global_step

            pkl_path = os.path.join(os.path.join(args.output_dir, path), "sampler_pos_start.pkl")
            if os.path.exists(pkl_path):
                with open(pkl_path, 'rb') as file:
                    _, first_epoch = pickle.load(file)
            else:
                first_epoch = global_step // num_update_steps_per_epoch
            print(f"Load pkl from {pkl_path}. Get first_epoch = {first_epoch}.")

            accelerator.print(f"Resuming from checkpoint {path}")
            accelerator.load_state(os.path.join(args.output_dir, path))

**Comment by bubbliiiing** [comment]
The details are in load_model_hook fn.
```python
pkl_path = os.path.join(input_dir, "sampler_pos_start.pkl")
if os.path.exists(pkl_path):
    with open(pkl_path, 'rb') as file:
        loaded_number, _ = pickle.load(file)
        batch_sampler.sampler._pos_start = max(loaded_number - args.dataloader_num_workers * accelerator.num_processes * 2, 0)
    print(f"Load pkl from {pkl_path}. Get loaded_number = {loaded_number}.")
```
I will close this issue first. If there is anything unclear, you can reopen it.
