### ISSUE TITLE
生成的视频，人物动作幅度非常小

### ISSUE THREAD

**Issue by DataAIPlayer** [aigc-apps/CogVideoX-Fun#23]
人物很少动，特别是图生视频

**Comment by bubbliiiing** [comment]
我们在重新训练一个在latent上添加noise的模型，用于增大动作幅度

**Comment by crj1998** [comment]
> 我们在重新训练一个在latent上添加noise的模型，用于增大动作幅度

能解释一下是什么意思吗？是加noise offset吗

**Comment by DataAIPlayer** [comment]
> 我们在重新训练一个在latent上添加noise的模型，用于增大动作幅度

不是训练集里视频动作幅度过小原因？

**Comment by phr00t** [comment]
> We're retraining a model that adds noise to latent to increase the amplitude of the motion

I've increased motion by increasing the strength of T5 and CLIP when encoding the prompt:

![image](https://github.com/user-attachments/assets/8f4ed826-2ba1-421d-996f-4f6109e70dd3)

Also, using different schedulers like SASolver helps significantly too:

![image](https://github.com/user-attachments/assets/fef828eb-2ac1-4530-8a61-436b894f1ba1)

I hope this is being considered, in addition to the original CogVideo I2V model, when you are training. I'm hoping that adding noise to the latents won't reduce quality when there are other methods of improving motion available.

**Comment by bubbliiiing** [comment]
> > 我们在重新训练一个在latent上添加noise的模型，用于增大动作幅度
> 
> 不是训练集里视频动作幅度过小原因？

二者我们都重新做了一下

**Comment by phr00t** [comment]
> > > We're retraining a model that adds noise to latent to increase the amplitude of the motion
> > 
> > 
> > I've increased motion by increasing the strength of T5 and CLIP when encoding the prompt:
> > ![image](https://private-user-images.githubusercontent.com/5983470/371626997-8f4ed826-2ba1-421d-996f-4f6109e70dd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjIwMTYsIm5iZiI6MTcyNzkyMTcxNiwicGF0aCI6Ii81OTgzNDcwLzM3MTYyNjk5Ny04ZjRlZDgyNi0yYmExLTQyMWQtOTk2Zi00ZjYxMDllNzBkZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDIxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYxNjk5YjhmMGI0NzM1YWIxYTNjODQzOWY4OGYwYzc1YWZhZjRmYTM5NTYzMzUzNTc1MjVmYmI2YzZlOTM1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8tm6ezjm2dMZPGL0wah_z5t39BsQ4quUomMqL7tCA0s)
> > Also, using different schedulers like SASolver helps significantly too:
> > ![image](https://private-user-images.githubusercontent.com/5983470/371627135-fef828eb-2ac1-4530-8a61-436b894f1ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjIwMTYsIm5iZiI6MTcyNzkyMTcxNiwicGF0aCI6Ii81OTgzNDcwLzM3MTYyNzEzNS1mZWY4MjhlYi0yYWMxLTQ1MzAtOGE2MS00MzZiODk0ZjFiYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDIxNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVkZmU4MjdmMTgyNWQwYTNlNzE5ZWQwZjU5NWIwYWRkMmE0MjUxMWMxZGJjOWQyN2Q4ZDExMWE5NTkyYTAyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Q3IrjIR-svzrvoctkfU0VZBhhVwMANN5EBH8sBaGZEE)
> > I hope this is being considered, in addition to the original CogVideo I2V model, when you are training. I'm hoping that adding noise to the latents won't reduce quality when there are other methods of improving motion available.
> 
> Does it only take 12 steps？

If I supply a starting and ending image, I can significantly reduce the number of steps and still get good results. I think this is because the model doesn't need to generate the details as they are already provided, and it can focus more on the motion. It really depends on the content and CLIP/T5 strength though... if the images are very different or I'm asking for lots of motion, more steps are needed.

**Comment by bubbliiiing** [comment]
Thank you.
