### ISSUE TITLE
can anyone please help me in installing cogvideox-fun step by step. iam facing with lot of errors like lot so, show some humanity and help this poor boy

### ISSUE THREAD

**Issue by SAT431** [aigc-apps/CogVideoX-Fun#25]
sathvik@sathvik:/mnt/c/Users/pasun/OneDrive/Desktop/AI/CogVideoX-Fun$ python3 app.py
/home/sathvik/.local/lib/python3.10/site-packages/gradio/components/dropdown.py:188: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: none or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Update diffusion transformer
loaded 3D transformer's pretrained weights from /mnt/c/Users/pasun/OneDrive/Desktop/AI/CogVideoX-Fun/models/Diffusion_Transformer/CogVideoX-Fun-5b-InP/transformer ...
Killed

**Comment by bubbliiiing** [comment]
It looks like your computer is running out of memory

**Comment by SAT431** [comment]
i have rtx 3060 gpu with 12gb vram and 24gb cpu ram. not that issue. canany one make spare some time and create orr organize like install in one click and run with bat file. it helps others alot right
