### ISSUE TITLE
GPU memory usage increases during training

### ISSUE THREAD

**Issue by wyyfffff** [aigc-apps/CogVideoX-Fun#30]
Thank you for your excellent work!

When I am training using train_control.py In 2 a800 gpu, I found my GPU memory usage has been increasing, slowly increasing from 65GB to 73GB. My batch size is 4, video resolution is 512x512. Is there any way to solve this problem?

Thank you!

**Comment by bubbliiiing** [comment]
This may be caused by the training strategy, as videos of different resolutions and lengths are trained together. If you expect the training memory usage to remain relatively constant, it's best to fix the resolution and length.
