### ISSUE TITLE
Seeking conda environment installation instruction for video caption

### ISSUE THREAD

**Issue by passerby233** [aigc-apps/CogVideoX-Fun#33]
I'm following the instruction in "cogvideox/video_caotion/README.md" to install with conda, however,  I'm unable to find the "Dockerfile.ds" mentioned in the README.md. Could you provide the "Dockerfile.ds" or the instruction for the installation of 'video caption + vila + Tinychat'?  I'm currently using docker, but conda is still more convenient for developing.

**Comment by yunkchen** [comment]
Sorry for our mistake, this Dockerfile is helpful.

https://github.com/aigc-apps/EasyAnimate/blob/main/Dockerfile.ds
