### ISSUE TITLE
Error on run - CogVideoX-Fun-V1.1-5b-InP is not the path to a directory containing a config.json file

### ISSUE THREAD

**Issue by adamreading** [aigc-apps/CogVideoX-Fun#36]
Full message LoadCogVideoX_Fun_Model
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /data/app/models/CogVideoX-Fun/CogVideoX-Fun-V1.1-5b-InP is not the path to a directory containing a config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

I have untar’d the file to the correct directory with all the model files in - but there is no config.json file in that zip file?

But I followed the instructions and unzipped into a directory called models/CogvideoX-Fun/Diffusion_Transformer 
![image](https://github.com/user-attachments/assets/8f7abe9f-976c-4d96-bb9e-f20803356985)

Do I need to move everything up one level and remove that extra folder? (On my cloud system this means deleting everything and starting again)

**Comment by bubbliiiing** [comment]
This seems to be caused by not fully unzipping.

**Comment by bubbliiiing** [comment]
Or re-git clone the weights on huggingface

**Comment by adamreading** [comment]
Thanks.  I solved it in the end by removing the Diffusion_transformer directory and manually recreating the hugging face directory structure and files one by one.

**Comment by Love-Glimpse** [comment]
> 谢谢。我最终通过删除 Diffusion_transformer 目录并手动逐个重新创建 hugging face 目录结构和文件解决了这个问题。

May I see your latest directory? Because I also encountered the same problem @adamreading

**Comment by HWT-WalterHu** [comment]
> > 谢谢。我最终通过删除 Diffusion_transformer 目录并手动逐个重新创建 hugging face 目录结构和文件解决了这个问题。
> 
> May I see your latest directory? Because I also encountered the same problem @adamreading

I suggest you to check the model path in the codes. Most of my cases were caused by wrong model path.

**Comment by adamreading** [comment]
> > > 谢谢。我最终通过删除 Diffusion_transformer 目录并手动逐个重新创建 hugging face 目录结构和文件解决了这个问题。
> > 
> > 
> > May I see your latest directory? Because I also encountered the same problem @adamreading
> 
> I suggest you to check the model path in the codes. Most of my cases were caused by wrong model path.

I did get it working in the end - the issue was actually my cloud server had 6Gb limit in zip files - so i had to move every file and directory one by one into their storage and then it worked - thank you
