### ISSUE TITLE
I2V 生成不符合输入图片的视频

### ISSUE THREAD

**Issue by O-O1024** [aigc-apps/CogVideoX-Fun#37]
![Gradio](https://github.com/user-attachments/assets/247e8fc0-2e07-4b66-a48b-e492c251f0fa)

**Comment by O-O1024** [comment]
还有一个问题，就是输入起始和结束图片，输出的视频开头发灰，也不渐变

https://github.com/user-attachments/assets/c84aad3a-28fc-4281-9ea8-9aab57a27268

**Comment by bubbliiiing** [comment]
> ![Gradio](https://private-user-images.githubusercontent.com/44624598/375982696-247e8fc0-2e07-4b66-a48b-e492c251f0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTg5NzcsIm5iZiI6MTcyODk1ODY3NywicGF0aCI6Ii80NDYyNDU5OC8zNzU5ODI2OTYtMjQ3ZThmYzAtMmUwNy00YjY2LWE0OGItZTQ5MmMyNTFmMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyMTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMWU3YzVmZmE1ZjMwNDlmNjVhYTlmNTZlMzY5OGUyNTcwZGU5NDc1ZGUyNTJlMDY4ODFlMWQzNDYxMmQ3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JiOX8RFTo9EF_0pabulTrotD3bD4IZIvw-TQhfduGzY)

这个看起来应该只是没有切换成功

**Comment by bubbliiiing** [comment]
> 还有一个问题，就是当有输入【起始】和【结束】图片时，输出的视频开头发灰，中间过程也不渐变
> 
>  009.mp4

可以试试Resize according to Reference，然后提示词尽量写一些动作。

**Comment by O-O1024** [comment]
> 这个看起来应该只是没有切换成功，就是还是文生视频

已经切换到 i2v 了
https://github.com/user-attachments/assets/cc990fe1-a69b-4e78-8fa4-36589b3b64d7
https://github.com/user-attachments/assets/65d6bd09-5c65-4bed-af50-95e3e8c4395d
