### ISSUE TITLE
No Gradient with Deepspeed

### ISSUE THREAD

**Issue by jzhang38** [aigc-apps/CogVideoX-Fun#44]
Hi, I tried to set the accelerate configs to deepspeed and then there is no gradient. (grad_norm = 0, no gradient, and model not updating).

It is fine under DDP(MULTI-GPU) and single GPU training.

**Comment by yunkchen** [comment]
Need more infos: share your config?

**Comment by jzhang38** [comment]
Sorry I realize I posted to a wrong repo.
