### ISSUE TITLE
An error occurred while building the environment. Can anyone help me?

### ISSUE THREAD

**Issue by xwwwwx429** [aigc-apps/CogVideoX-Fun#48]
![image](https://github.com/user-attachments/assets/b8d1b6a9-6526-436a-b22d-6cff42a0ec91)

**Comment by yunkchen** [comment]
whole log is better~
could try to delete pip cache and install deepspeed again.

**Comment by yunkchen** [comment]
whole log is better~
could try to delete pip cache and install deepspeed again.

**Comment by 0m0Ding** [comment]
> whole log is better~ 整根木头更好~ could try to delete pip cache and install deepspeed again.可以尝试删除 pip 缓存并再次安装 Deepspeed。

well, how try to delete pip cache and install deepspeed again.

**Comment by 0m0Ding** [comment]
> ![image](https://private-user-images.githubusercontent.com/134383432/380029535-b8d1b6a9-6526-436a-b22d-6cff42a0ec91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzEzNDQsIm5iZiI6MTczMDI3MTA0NCwicGF0aCI6Ii8xMzQzODM0MzIvMzgwMDI5NTM1LWI4ZDFiNmE5LTY1MjYtNDM2YS1iMjJkLTZjZmY0MmEwZWM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNjUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjc3MDhhNzI2ZThlNjNkNjVjNGUzMTNlZTY0MGU3OWI4NGQyYTZlMWE0NzBiZDE2OTA2MWUwNjBhZGNmZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HXaSy4ZmaNnRXGyqUmSTnw-T_ovOLGLj5LSoiQ1oNrM)
well, are you ok?

**Comment by wx331406** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/134383432/380029535-b8d1b6a9-6526-436a-b22d-6cff42a0ec91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzEzNDQsIm5iZiI6MTczMDI3MTA0NCwicGF0aCI6Ii8xMzQzODM0MzIvMzgwMDI5NTM1LWI4ZDFiNmE5LTY1MjYtNDM2YS1iMjJkLTZjZmY0MmEwZWM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNjUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjc3MDhhNzI2ZThlNjNkNjVjNGUzMTNlZTY0MGU3OWI4NGQyYTZlMWE0NzBiZDE2OTA2MWUwNjBhZGNmZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HXaSy4ZmaNnRXGyqUmSTnw-T_ovOLGLj5LSoiQ1oNrM)
> > 那你还好吗？

遇到同样的问题，你的问题解决了吗？我完全按照要求安装的，但是提示检测不到torch

**Comment by 0m0Ding** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/134383432/380029535-b8d1b6a9-6526-436a-b22d-6cff42a0ec91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzEzNDQsIm5iZiI6MTczMDI3MTA0NCwicGF0aCI6Ii8xMzQzODM0MzIvMzgwMDI5NTM1LWI4ZDFiNmE5LTY1MjYtNDM2YS1iMjJkLTZjZmY0MmEwZWM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNjUwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjc3MDhhNzI2ZThlNjNkNjVjNGUzMTNlZTY0MGU3OWI4NGQyYTZlMWE0NzBiZDE2OTA2MWUwNjBhZGNmZWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HXaSy4ZmaNnRXGyqUmSTnw-T_ovOLGLj5LSoiQ1oNrM)
> > > 那你还好吗？
> 
> 遇到同样的问题，你的问题解决了吗？我完全按照要求安装的，但是提示检测不到torch

好久之前的事了，我已经解决了把，我也不记得是啥问题了，不过torch可以在轮子上下载安装，或者你电脑的进行修复一下
