### ISSUE TITLE
finetune pose-5b out of memory

### ISSUE THREAD

**Issue by junwuzhang19** [aigc-apps/CogVideoX-Fun#49]
Thanks for your great work! I finetune pose-5b using a single A100 80G using train_control.sh, but got out of memory. The  training script is unchanged other than the model size. I wonder how to finetune pose-5b model on 80G GPU. thanks!

**Comment by yunkchen** [comment]
Another machine with more than one 80G GPU is all you need.

**Comment by HWT-WalterHu** [comment]
Could you show me  how to organize the pose infos, write poses into meta-file or sequence of pose image? I am trying to finetune the pose controlled model but dont know how to organize data. Thanks

**Comment by bubbliiiing** [comment]
As shown in https://github.com/aigc-apps/CogVideoX-Fun/blob/main/scripts/README_TRAIN_CONTROL.md.
