### ISSUE TITLE
How to Use the Pose Model in CogVideoX

### ISSUE THREAD

**Issue by whois206** [aigc-apps/CogVideoX-Fun#54]
How can I effectively use the CogVideoX-Fun-V1.1-2b-Pose model to generate videos with pose guidance? Specifically, I would like to know if it can combine both image and pose inputs to control the generated video frames. Additionally, are there any particular settings or parameter adjustments recommended to achieve smoother animation or higher fidelity?”

**Comment by 4lt3r3go** [comment]
i coudnt find any infos about the pose model either. i hope someone solve this mistery.
it is incredible the amount of effort such people do in terms of energy, time and money, to create such incredible models
and then there's ZERO informations about how to use them 😁

**Comment by bubbliiiing** [comment]
We are currently still in development; the pose model only supports input of control information and does not support reference images.
