### ISSUE TITLE
train_mode parameter documentation is nonsensical

### ISSUE THREAD

**Issue by orcinus** [aigc-apps/CogVideoX-Fun#58]
According to documentation here:

https://github.com/aigc-apps/CogVideoX-Fun/blame/4de9773025a621824172ff61b5b7963ac18fd0e5/scripts/README_TRAIN_LORA.md#L15

> `train_mode` is used to specify the training mode, which can be either normal or inpaint. Since CogVideoX-Fun uses the Inpaint model to achieve **text-to-video generation**, the default is set to inpaint mode. If you only wish to achieve **text-to-video generation**, you can remove this line, and it will default to the **text-to-video mode**.

So:
- set to inpaint for text-to-video
- set to normal for text-to-video

What is the difference? :)
I am guessing one of these was supposed to say **image-to-video** instead.

**Comment by bubbliiiing** [comment]
Sorry, I will fix it.

**Comment by orcinus** [comment]
Thank you! <3
