### ISSUE TITLE
How to organize data to finetune pose-control model ?

### ISSUE THREAD

**Issue by HWT-WalterHu** [aigc-apps/CogVideoX-Fun#60]
I didn't see guidance on the method to prepare pose data. Should them be wrote into meta-file or plotted into sequence of images/videos ?

**Comment by bubbliiiing** [comment]
Just a pose mp4.

**Comment by bubbliiiing** [comment]
https://github.com/aigc-apps/CogVideoX-Fun/blob/main/scripts/README_TRAIN_CONTROL.md

**Comment by HWT-WalterHu** [comment]
Thanks

**Comment by HWT-WalterHu** [comment]
Problem solved

**Comment by RunqiWang77** [comment]
> https://github.com/aigc-apps/CogVideoX-Fun/blob/main/scripts/README_TRAIN_CONTROL.md

Hello, this file is currently unavailable. Could you advise which document I should check for the related information?

**Comment by yunkchen** [comment]
> > https://github.com/aigc-apps/CogVideoX-Fun/blob/main/scripts/README_TRAIN_CONTROL.md
> 
> Hello, this file is currently unavailable. Could you advise which document I should check for the related information?

https://github.com/aigc-apps/VideoX-Fun/blob/main/scripts/wan2.1_fun/README_TRAIN_CONTROL.md
