### ISSUE TITLE
Inference with finetuned checkpoints

### ISSUE THREAD

**Issue by Closertodeath** [aigc-apps/CogVideoX-Fun#61]
Could you provide documentation on running inference with a finetuned Cogvideox-fun model? My finetune has output into something other than diffusers, and it seems like inference only supports the original diffusers format.

**Comment by yunkchen** [comment]
Could you list your finetuned model dir?

**Comment by Closertodeath** [comment]
> Could you list your finetuned model dir?

![image](https://github.com/user-attachments/assets/d7dfd239-c5ef-4c6c-9bfe-cc31e17bb9fb)

**Comment by bubbliiiing** [comment]
If you use predict_t2v.py, you can modify the transformer_path
![image](https://github.com/user-attachments/assets/bb1e2c59-80c6-4d66-a88c-2816b4f9776e)
