### ISSUE TITLE
4卡deepspeed训练采样器top xx 10打印相同数据

### ISSUE THREAD

**Issue by ericthesolid** [aigc-apps/CogVideoX-Fun#64]
请问是否正常
xx top 10 [19350, 498, 30384, 18997, 29190, 21190, 30604, 29550, 25494, 14597] 0
xx top 10 [19350, 498, 30384, 18997, 29190, 21190, 30604, 29550, 25494, 14597] 0
xx top 10 [19350, 498, 30384, 18997, 29190, 21190, 30604, 29550, 25494, 14597] 0
xx top 10 [19350, 498, 30384, 18997, 29190, 21190, 30604, 29550, 25494, 14597] 0

**Comment by bubbliiiing** [comment]
正常的

**Comment by xiangweifeng** [comment]
> 正常的

没太理解，那不是没块卡都训练相同的数据了吗

**Comment by bubbliiiing** [comment]
accelerate这个引擎是所有node都会过一遍sampler，但主node负责分发，所以不影响。

**Comment by xiangweifeng** [comment]
> accelerate这个引擎是所有node都会过一遍sampler，但主node负责分发，所以不影响。

谢谢大佬。也就是说非主节点过一遍 Sampler，只是做做样子，只有主node 的才有效对吧。
