### ISSUE TITLE
resume from checkpoint for loras?

### ISSUE THREAD

**Issue by Zebraslive** [aigc-apps/CogVideoX-Fun#65]
Is the resume from checkpoint broken for loras training? I can't get it to work. 

When using --resume_from_checkpoint="latest" i get this
```
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/CogVideoX-Fun/scripts/train_lora.py", line 1629, in <module>
    main()
  File "/teamspace/studios/this_studio/CogVideoX-Fun/scripts/train_lora.py", line 1208, in main
    dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
  File "/teamspace/studios/this_studio/CogVideoX-Fun/scripts/train_lora.py", line 1208, in <lambda>
    dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
ValueError: invalid literal for int() with base 10: '100.safetensors'
```

**Comment by Zebraslive** [comment]
> Have you renamed safetensors file?

No the checkpoints are saved in original format. checkpoint-xxx.safetensors

**Comment by bubbliiiing** [comment]
Please add --save_state

**Comment by Zebraslive** [comment]
> Please add --save_state

Thanks you!

**Comment by Zebraslive** [comment]
> Please add --save_state

Am i missing something else? 
when using save_state i get this error  No such file or directory: 'output_dir_smallFlash2/checkpoint-30/pytorch_model.bin' 

this is the line 1236 accelerator.load_state(os.path.join(args.output_dir, path))

```
11/14/2024 01:30:47 - INFO - __main__ - ***** Running training *****
11/14/2024 01:30:47 - INFO - __main__ -   Num examples = 5
11/14/2024 01:30:47 - INFO - __main__ -   Num Epochs = 270
11/14/2024 01:30:47 - INFO - __main__ -   Instantaneous batch size per device = 1
11/14/2024 01:30:47 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
11/14/2024 01:30:47 - INFO - __main__ -   Gradient Accumulation steps = 1
11/14/2024 01:30:47 - INFO - __main__ -   Total optimization steps = 1350
Load pkl from output_dir_smallFlash2/checkpoint-30/sampler_pos_start.pkl. Get first_epoch = 0.
[2024-11-14 01:30:47,865] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
missing keys: 0, unexpected keys: 0
Resuming from checkpoint checkpoint-30
11/14/2024 01:30:49 - INFO - accelerate.accelerator - Loading states from output_dir_smallFlash2/checkpoint-30
Load pkl from output_dir_smallFlash2/checkpoint-30/sampler_pos_start.pkl. Get loaded_number = 0.
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/CogVideoX-Fun/scripts/train_lora.py", line 1629, in <module>
    main()
  File "/teamspace/studios/this_studio/CogVideoX-Fun/scripts/train_lora.py", line 1236, in main
    accelerator.load_state(os.path.join(args.output_dir, path))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/accelerate/accelerator.py", line 3231, in load_state
    override_attributes = load_accelerator_state(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/accelerate/checkpointing.py", line 221, in load_accelerator_state
    state_dict = load(input_model_file, map_location=map_location)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/accelerate/utils/other.py", line 254, in load
    loaded_obj = torch.load(f, map_location=map_location, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'output_dir_smallFlash2/checkpoint-30/pytorch_model.bin'
```

```
accelerate launch --mixed_precision="bf16" scripts/train_lora.py \
  --pretrained_model_name_or_path="$MODEL_NAME" \
  --train_data_dir="$DATASET_NAME" \
  --train_data_meta="$DATASET_META_NAME" \
  --image_sample_size=1280 \
  --video_sample_size=720 \
  --token_sample_size=720 \
  --video_sample_stride=3 \
  --video_sample_n_frames=53 \
  --train_batch_size=1 \
  --video_repeat=1 \
  --gradient_accumulation_steps=1 \
  --dataloader_num_workers=8 \
  --num_train_epochs=50 \
  --max_train_steps=1350 \
  --checkpointing_steps=30 \
  --learning_rate=1e-04 \
  --seed=42 \
  --output_dir="output_dir_smallFlash2" \
  --gradient_checkpointing \
  --mixed_precision="bf16" \
  --adam_weight_decay=3e-2 \
  --adam_epsilon=1e-10 \
  --vae_mini_batch=1 \
  --max_grad_norm=0.05 \
  --random_hw_adapt \
  --training_with_video_token_length \
  --enable_bucket \
  --low_vram \
  --save_state \
  --resume_from_checkpoint="latest" \
  --train_mode="inpaint"
  ```

please let me know. thanks!

**Comment by ZhangHuixin1103** [comment]
@Zebraslive same bro. would you mind telling me how to solve the `pytorch_model.bin` issue?

**Comment by Zebraslive** [comment]
> @Zebraslive same bro. would you mind telling me how to solve the `pytorch_model.bin` issue?

For resume to work it must finish running the max train steps or epoch. Also make sure you are using save_state. 

It should create a folder of states with the  bin file. you can't resume directly from safetensors.

**Comment by ZhangHuixin1103** [comment]
@Zebraslive Thanks for the quick reply ^^

Yes I used a --save_state, the checkpoint now looks like:
```shell
- checkpoint-50
    - optimizer.bin
    - scheduler.bin
    - random_states_0.pkl
    - sampler_pos_start.pkl
    - lora_diffusion_pytorch_model.safetensors
- checkpoint-100
- ...
```

Would you tell me does this seem reasonable? Is there anything else I can do? I still cannot locate the pytorch_model.bin.

**Comment by Zebraslive** [comment]
> @Zebraslive Thanks for the quick reply ^^
> 
> Yes I used a --save_state, the checkpoint now looks like:
> ```shell
> - checkpoint-50
>     - optimizer.bin
>     - scheduler.bin
>     - random_states_0.pkl
>     - sampler_pos_start.pkl
>     - lora_diffusion_pytorch_model.safetensors
> - checkpoint-100
> - ...
> ```
> 
> Would you tell me does this seem reasonable? Is there anything else I can do? I still cannot locate the pytorch_model.bin.

@ZhangHuixin1103 this looks correct but it's been a while since I trained using this script. Did you try using resume with "latest"? If you didn't use save_state before then you might need to start over with fresh train. That's what i had to do.

 If you can you should just switch to using this for training https://github.com/alisson-anjos/diffusion-pipe-ui it's much easier. Though I don't known if it supports control lora.

**Comment by Zebraslive** [comment]
@ZhangHuixin1103 from what I can remember the bin file that's needed is only created once the full training session is completed.

**Comment by ZhangHuixin1103** [comment]
Thanks so much for your immediate help.
Yes I used a "latest".

I see. So by "full training session is completed", you mean I have to wait for 30,000 steps if there are 30,000 steps in total, to get the pytorch_model.bin generated, then resume from checkpoint-30000? 😂

Gosh I guess I need to manually shorten the training process. Thank you again!

**Comment by Zebraslive** [comment]
> @Zebraslive Thanks so much for your immediate help.
> Yes I used a "latest".
> 
> I see. So by "full training session is completed", you mean I have to wait for 30,000 steps if there are 30,000 steps in total, to get the pytorch_model.bin generated, then resume from checkpoint-30000? 😂
> 
> Gosh I guess I need to manually shorten the training process. Thank you again!

@ZhangHuixin1103 Yes but  just to be sure you can test this with a very short train to see if it creates the file.

**Comment by ZhangHuixin1103** [comment]
@Zebraslive Copy that. Wish you a nice one 😘

**Comment by sunjian2015** [comment]
What should i do if i am not add --save_state when i train my model?
