### ISSUE TITLE
trainable_modules = ['ff.net', 'pos_embed', 'attn2', 'proj_out', 'timepositionalencoding', 'h_position', 'w_position']

### ISSUE THREAD

**Issue by chenchao15** [aigc-apps/CogVideoX-Fun#68]
请问如果pose control的模型使用trainable_modules = ['ff.net', 'pos_embed', 'attn2', 'proj_out', 'timepositionalencoding', 'h_position', 'w_position']来指定训练部分参数【代码中注释的部分】，效果会相比全参数有明显下降吗？
<img width="1014" alt="企业微信截图_9fd8b945-3c7d-419e-83ed-21567c575827" src="https://github.com/user-attachments/assets/cec05f04-8a0e-441a-a72f-47c76d39c3a0">

**Comment by bubbliiiing** [comment]
额，这个只是一个以前在EasyAnimate的示例，实际要写的模块名称应该不是这些。
在这里应该是
transformer_blocks.0.
transformer_blocks.1.
这样

**Comment by bubbliiiing** [comment]
我先关闭此issue，如果有不理解的地方，可以重新打开。
