### ISSUE TITLE
Why is my test case not moving? All the parameter settings are the same.

### ISSUE THREAD

**Issue by Lsen991031** [aigc-apps/CogVideoX-Fun#7]
Uploading 00000

https://github.com/user-attachments/assets/0b0a915a-04eb-4ff8-ba5f-0d7e5120734b

https://github.com/user-attachments/assets/1e188467-67c9-4df0-ab06-30f5fa1c3b5d

https://github.com/user-attachments/assets/f29fbf46-3fac-4777-8873-84a3c99f35c3

**Comment by bubbliiiing** [comment]
Could you please write some actions in the positive prompt words.

**Comment by dctnorin** [comment]
> Uploading 00000
> 
>  00000003.mp4 
>  00000002.mp4 
>  00000001.mp4

When I used the predict_i2v.py, something went wrong.
ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.

Have you ever had this kind of problem?

**Comment by jasoncow007** [comment]
same result,,,,, dont know why

**Comment by djdookie** [comment]
I have the same "no motion" issue with the CogVideoX-Fun-5B model. Sometimes not much motion with the 2B model, sometimes it's ok. Tried all parameters.

**Comment by bubbliiiing** [comment]
I will close this issue first. If there is anything unclear, you can reopen it.
