### ISSUE TITLE
Nvidia APEX 报错

### ISSUE THREAD

**Issue by zmqgmy** [aigc-apps/CogVideoX-Fun#70]
我最早用的是官方提供的图生视频，只正常运行的。然后我看到有一条提示
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Please 'pip install apex'
于是我想尽办法安装了 Nvidia APEX
然后就不能正常使用了报错如下：
expected scalar type Float but found Half

**Comment by hkunzhe** [comment]
@zmqgmy 具体的环境是什么呢？如果只是提示没有出错的话，就不需要管 apex。训练和推理都没有这个依赖。

**Comment by zmqgmy** [comment]
> @zmqgmy 具体的环境是什么呢？如果只是提示没有出错的话，就不需要管 apex。训练和推理都没有这个依赖。

我又卸载了APEX  可以正常使用，linux的系统，可能是我的GPU比较老的原因吧，P100 的GPU
