### ISSUE TITLE
how to train i2v from cogvideox-2b model

### ISSUE THREAD

**Issue by jianlong-yuan** [aigc-apps/CogVideoX-Fun#72]
error : RuntimeError: Given groups=1, weight of size [1920, 16, 2, 2], expected input[24, 33, 24, 42] to have 16 channels, but got 33 channels instead

**Comment by bubbliiiing** [comment]
You need to change the config in models/Diffusion_Transformer/CogVideoX-Fun-2b/transformer/config.json
{
  "_class_name": "CogVideoXTransformer3DModel",
  "_diffusers_version": "0.30.0.dev0",
  "activation_fn": "gelu-approximate",
  "attention_bias": true,
  "attention_head_dim": 64,
  "dropout": 0.0,
  "flip_sin_to_cos": true,
  "freq_shift": 0,
  "in_channels": 33,
  "max_text_seq_length": 226,
  "norm_elementwise_affine": true,
  "norm_eps": 1e-05,
  "num_attention_heads": 30,
  "num_layers": 30,
  "out_channels": 16,
  "patch_size": 2,
  "sample_frames": 49,
  "sample_height": 60,
  "sample_width": 90,
  "spatial_interpolation_scale": 1.875,
  "temporal_compression_ratio": 4,
  "temporal_interpolation_scale": 1.0,
  "text_embed_dim": 4096,
  "time_embed_dim": 512,
  "timestep_activation_fn": "silu"
}

**Comment by bubbliiiing** [comment]
I will close this issue first. If there is anything unclear, you can reopen it.

**Comment by AlphaNext** [comment]
@bubbliiiing Hi, I'am using **CogVideoX-Fun-V1.1-5b-Control** model to fine tuning, deepspeed type, and get the following error, my **control_file_path** videos are 3 channels edge maps, the size of them are same as the **file_path** videos.
 
```
RuntimeError: Given groups=1, weight of size [3072, 32, 2, 2], expected input[12, 16, 60, 104] to have 32 channels, but got 16 channels instead
```
