### ISSUE TITLE
HOW TO CONNECT THE LORAS?

### ISSUE THREAD

**Issue by lior007** [aigc-apps/CogVideoX-Fun#78]
LINK TO LORAS I DOWNLOAD
https://huggingface.co/alibaba-pai/CogVideoX-Fun-V1.1-Reward-LoRAs/tree/main

I DONT SEE ANY OPTION IN THE WORKFLOWS.
I MEAN TO THIS LORAS
CogVideoX-Fun-V1.1-5B with Reward Backpropagation

**Comment by bubbliiiing** [comment]
Demo json can be found in https://github.com/aigc-apps/CogVideoX-Fun/pull/79.

**Comment by philpilkington** [comment]
Or put the appropriate one in CogVideoX-Fun/models/Personalized_Model and you can see them in the app.py gui interface
