### ISSUE TITLE
想请问一下，如果是图生视频，输入是啥

### ISSUE THREAD

**Issue by tangdong1994** [aigc-apps/CogVideoX-Fun#81]
也就是noisy latent+mask+video latent，mask分别用0，1表示，video需要预测的帧用0图占位？

**Comment by bubbliiiing** [comment]
0图是什么，黑色图吗

**Comment by tangdong1994** [comment]
> 0图是什么，黑色图吗

是的，我看你们pipeline里面是用的-1图占位，应该是黑图归一化之后的结果？还有就是你们mask输入的是不是全0或者全1的呢，我发现我的结果出来的有点问题，我的情况是第0帧是图片，直接回贴回来，mask为1的位置好像也直接回贴回来了。没有起到图生视频的效果，所以我想了解，你们输入的tensor到底是怎么设置的呢？辛苦帮忙解答一下

https://github.com/user-attachments/assets/e50e0292-b528-4fb4-a4b1-4bf8dd929a2f

**Comment by bubbliiiing** [comment]
1、是的，我看你们pipeline里面是用的-1图占位，应该是黑图归一化之后的结果？
是的
2、还有就是你们mask输入的是不是全0或者全1的呢
是的
3、我的情况是第0帧是图片，直接回贴回来，mask为1的位置好像也直接回贴回来了
这一段我看不太懂是什么意思
4、你们输入的tensor到底是怎么设置的呢
像素部分 需要保留的帧按照原值加噪声后输入，需要重建的帧设置为黑
mask部分 需要保留的帧为1，需要重建的帧为0

**Comment by tangdong1994** [comment]
> 1、是的，我看你们pipeline里面是用的-1图占位，应该是黑图归一化之后的结果？ 是的 2、还有就是你们mask输入的是不是全0或者全1的呢 是的 3、我的情况是第0帧是图片，直接回贴回来，mask为1的位置好像也直接回贴回来了 这一段我看不太懂是什么意思 4、你们输入的tensor到底是怎么设置的呢 像素部分 需要保留的帧按照原值加噪声后输入，需要重建的帧设置为黑 mask部分 需要保留的帧为1，需要重建的帧为0

是这样的，因为我想试用你们模型的图生视频的功能，mask部分我设定的第一个位置是1，后面的位置都是0，然后inpainting的latent部分，第一个位置是我要生视频的图片，后面的是归一化之后的黑图，也就是-1图片，但是我发现我的结果为啥会出现上年的结果，直接把黑图和图片给生成出来了，没有达到图生视频的结果

**Comment by tangdong1994** [comment]
不好意思，我仔细验证了一下，我的mask反了，mask部分 需要保留的帧为0，需要重建的帧为1，搞反了
