### ISSUE TITLE
If the finetuned 2B model using RoPE or fixed position embedding?

### ISSUE THREAD

**Issue by Kyfafyd** [aigc-apps/CogVideoX-Fun#9]
R.T.

**Comment by bubbliiiing** [comment]
This may need to be re-fine-tuned.

**Comment by Kyfafyd** [comment]
Thanks for your response!
But I am asking about if your finetuned 2B model is using RoPE or the basic 3d pos embedding used in original CogVideoX?

**Comment by bubbliiiing** [comment]
Sorry, the basic 3d pos embedding used in original CogVideoX.
