### ISSUE TITLE
CogVideoX-Fun-V1.5-5B-InP 是基于CogVideoX-5B-1.5版本训练的吗？另外是是否支持reward 1.1？

### ISSUE THREAD

**Issue by zaitaxiang2012** [aigc-apps/CogVideoX-Fun#99]

**Comment by hkunzhe** [comment]
@zaitaxiang2012 是的。不支持 reward 1.1，可以用对应的 reward 1.5，https://huggingface.co/alibaba-pai/CogVideoX-Fun-V1.5-Reward-LoRAs
